export const IPC_CHANNELS = {
  OMP_DETECT: 'omp:detect',
  OMP_CAPABILITIES: 'omp:capabilities',
  OMP_CREATE_SESSION: 'omp:create-session',
  OMP_SEND_MESSAGE: 'omp:send-message',
  OMP_KILL_SESSION: 'omp:kill-session',
  OMP_ABORT_SESSION: 'omp:abort-session',
  OMP_SESSION_EVENT: 'omp:session-event',
  OMP_LIST_SESSIONS: 'omp:list-sessions',
  OMP_INSTALL: 'omp:install',
  OMP_INSTALL_STATUS: 'omp:install-status',
  FS_LIST_DIR: 'fs:list-dir',
  FS_READ_FILE: 'fs:read-file',
  /** @deprecated Workspace authority is grant-based; kept only for back-compat during transition. */
  FS_SET_ROOT: 'fs:set-root',
  FS_LIST_PROJECT_FILES: 'fs:list-project-files',
  WORKSPACE_SELECT: 'workspace:select',
  WORKSPACE_ACTIVATE_RECENT: 'workspace:activate-recent',
  WORKSPACE_LIST_RECENT: 'workspace:list-recent',
  WORKSPACE_CLEAR_RECENT: 'workspace:clear-recent',
  WORKSPACE_REMOVE_RECENT: 'workspace:remove-recent',
  WORKSPACE_ACTIVATE: 'workspace:activate',
  WORKSPACE_REVOKE: 'workspace:revoke',
  WORKSPACE_LIST: 'workspace:list',
  PACKAGES_LIST: 'packages:list',
  PACKAGES_CAPABILITIES: 'packages:capabilities',
  PACKAGES_SEARCH: 'packages:search',
  PACKAGES_INSTALL: 'packages:install',
  /** Native local source picker → opaque, short-lived package source grant. */
  PACKAGES_SELECT_LOCAL_SOURCE: 'packages:select-local-source',
  /** Trusted preload File extraction → opaque local package source grant. */
  PACKAGES_GRANT_DROPPED_LOCAL_SOURCE: 'packages:grant-dropped-local-source',
  /** Install a Main-held local package source; never accepts a filesystem path. */
  PACKAGES_INSTALL_LOCAL_SOURCE: 'packages:install-local-source',
  PACKAGES_REMOVE: 'packages:remove',
  PACKAGES_UPDATE: 'packages:update',
  PACKAGES_SET_ENABLED: 'packages:set-enabled',
  /** Read-only health/configuration state for the user-installed Kimi CU runtime. */
  KIMI_CU_STATUS: 'kimi-cu:status',
  /** Explicitly add/remove OMP GUI's managed Kimi CU MCP registration. */
  KIMI_CU_SET_ENABLED: 'kimi-cu:set-enabled',
  MANAGED_PLUGINS_LIST: 'managed-plugins:list',
  MANAGED_PLUGINS_GET: 'managed-plugins:get',
  MANAGED_PLUGINS_SAVE: 'managed-plugins:save',
  MANAGED_PLUGINS_SYNC: 'managed-plugins:sync',
  MANAGED_PLUGINS_DELETE: 'managed-plugins:delete',
  PLUGINS_SCAFFOLD: 'plugins:scaffold',
  /** Native directory picker → opaque, one-scaffold DirectoryGrant. */
  PLUGINS_SCAFFOLD_SELECT_DIRECTORY: 'plugins:scaffold-select-directory',
  /** Reveal a Main-held scaffold output; never accepts a renderer path. */
  PLUGINS_SCAFFOLD_REVEAL: 'plugins:scaffold-reveal',
  /** Install a Main-held scaffold output; never accepts a renderer path. */
  PLUGINS_SCAFFOLD_INSTALL: 'plugins:scaffold-install',
  STORE_GET: 'store:get',
  STORE_SET: 'store:set',
  BOARDS_LIST: 'boards:list',
  BOARDS_SAVE: 'boards:save',
  BOARDS_DELETE: 'boards:delete',
  BOARDS_APPEND_NOTE: 'boards:append-note',
  BOARDS_DATASETS_LIST: 'boards:datasets-list',
  /** Native file picker → opaque, one-import FileGrant. */
  BOARDS_DATASETS_SELECT_FILE: 'boards:datasets-select-file',
  /** Trusted preload File extraction → opaque, one-import FileGrant. */
  BOARDS_DATASETS_GRANT_DROPPED_FILE: 'boards:datasets-grant-dropped-file',
  BOARDS_DATASETS_IMPORT: 'boards:datasets-import',
  BOARDS_DATASETS_DELETE: 'boards:datasets-delete',
  BOARDS_DATASETS_RENAME: 'boards:datasets-rename',
  DIALOG_SELECT_FOLDER: 'dialog:select-folder',
  DIALOG_SELECT_FILE: 'dialog:select-file',
  DIALOG_SELECT_IMAGE: 'dialog:select-image',
  SHELL_SHOW_CLI_SETTINGS: 'shell:show-cli-settings',
  SHELL_OPEN_EXTERNAL_URL: 'shell:open-external-url',
  OMP_RESPOND_UI: 'omp:respond-ui',
  OMP_SET_MODEL: 'omp:set-model',
  OMP_SESSION_STATS: 'omp:session-stats',
  OMP_LIST_COMMANDS: 'omp:list-commands',
  OMP_COMPACT: 'omp:compact',
  PI_GET_MODEL_CONFIG: 'pi:get-model-config',
  PI_SET_MODEL_CONFIG: 'pi:set-model-config',
  PI_SET_API_KEY: 'pi:set-api-key',
  PI_CLEAR_API_KEY: 'pi:clear-api-key',
  PI_LIST_MODELS: 'pi:list-models',
  PI_LIST_CATALOG_MODELS: 'pi:list-catalog-models',
  PI_SET_MACHINE_SKILLS: 'pi:set-machine-skills',
  PI_LIST_MACHINE_SKILLS: 'pi:list-machine-skills',
  APP_VERSION: 'app:version',
  OMP_STEER: 'omp:steer',
  OMP_FOLLOW_UP: 'omp:follow-up',
  OMP_SET_THINKING: 'omp:set-thinking',
  OMP_UPDATE_APPROVAL_CONFIG: 'omp:update-approval-config',
  OMP_EXPORT_HTML: 'omp:export-html',
  OMP_SESSION_STATE: 'omp:session-state',
  OMP_LIST_SESSION_HISTORY: 'omp:list-session-history',
  OMP_RESUME_SESSION: 'omp:resume-session',
  OMP_DELETE_SESSION_FILE: 'omp:delete-session-file',
  OMP_SET_SESSION_NAME: 'omp:set-session-name',
  OMP_GET_SUBAGENTS: 'omp:get-subagents',
  OMP_GET_SUBAGENT_MESSAGES: 'omp:get-subagent-messages',
  CHECKPOINT_CREATE: 'checkpoint:create',
  CHECKPOINT_LIST: 'checkpoint:list',
  CHECKPOINT_RESTORE: 'checkpoint:restore',
  GIT_INFO: 'git:info',
  GIT_FILE_DIFF: 'git:file-diff',
  UPDATER_STATUS: 'updater:status',
  UPDATER_GET_STATUS: 'updater:get-status',
  UPDATER_CHECK: 'updater:check',
  UPDATER_DOWNLOAD: 'updater:download',
  UPDATER_QUIT_INSTALL: 'updater:quit-install',
  UPDATER_OPEN_PAGE: 'updater:open-release-page',
  NOTIFY_SELECT_SESSION: 'notify:select-session',
  RUNTIME_OVERVIEW: 'runtime:overview',
  RUNTIME_LIST_MODELS: 'runtime:list-models',
  RUNTIME_LIST_MODEL_CATALOG: 'runtime:list-model-catalog',
  RUNTIME_REFRESH_MODEL_CATALOG: 'runtime:refresh-model-catalog',
  RUNTIME_SET_DEFAULT_MODEL: 'runtime:set-default-model',
  RUNTIME_SET_DEFAULT_THINKING: 'runtime:set-default-thinking',
  RUNTIME_SET_MACHINE_SKILLS: 'runtime:set-machine-skills',
  CUSTOM_PROVIDERS_LIST: 'custom-providers:list',
  CUSTOM_PROVIDERS_SAVE: 'custom-providers:save',
  CUSTOM_PROVIDERS_DELETE: 'custom-providers:delete',
  AUTH_START_LOGIN: 'auth:start-login',
  AUTH_SET_API_KEY: 'auth:set-api-key',
  AUTH_ANSWER_LOGIN: 'auth:answer-login',
  AUTH_CANCEL_LOGIN: 'auth:cancel-login',
  AUTH_LOGOUT: 'auth:logout',
  AUTH_OPEN_LOGIN_URL: 'auth:open-login-url',
  AUTH_LOGIN_STATE: 'auth:login-state'
} as const
